image: ubuntu:trusty

before_script:
 - apt-get install -y python3
 - npm install -g lix
 - lix download

test:
  script:
   - haxe tests.hxml --interp
   - haxe tests.hxml -python bin/tests.py && python bin/tests.py

