image: osakared/haxe-ci

before_script:
 - haxelib install hxcpp
 - haxelib install hxjava
 - lix download

test:
  script:
   - haxe tests.hxml --interp
   - haxe tests.hxml -python bin/tests.py           && python3 bin/tests.py
   - haxe tests.hxml -lib hxnodejs -js bin/tests.js && node bin/tests.js
   - haxe tests.hxml -java bin                      && java -jar bin/tests.jar

